<span 	style="white-space: nowrap; font-weight: bold;" 
		title="Click here to see the primary goal of this page. (Additional vulnerabilities will exist on a page)">
	<a 	href="./includes/pop-up-help-context-generator.php?pagename=<?php echo $lPage; ?>" 
		class="colorbox"
		title="Help me with page <?php echo $lPage; ?>" style="color: #000000;">
		<img alt="Help Me!" align="middle" src="./images/help-easy-button-48-48.png" />
		Help Me!
	</a>
</span>