			<br/><br/>
			<span class="report-header">Overview</span>
			<br/><br/>
			Directory Browsing is allowed when the web server is misconfigured to show the
			user the contents of directories on the server.
<br/><br/>
<a href="#videos" class="label"><img alt="YouTube" src="/images/youtube-play-icon-40-40.png" style="margin-right: 10px;" />Video Tutorials</a>
<br/><br/>
<span class="report-header">Discovery Methodology</span>
<br/><br/>
Use search engines to look for pages which include "index of" in the title.
Additionally attempt to read the robots.txt file and spider the application
with a tool such as Burp-Suite, OWASP ZAP, or Nikto, and directories
named by search engines.
<br/><br/>
<span class="report-header">Exploitation</span>
<br/><br/>
Catalog and inspect the folders named in robots.txt and any directories
discovered during spidering. Use a tool such as Burp-Intruder to brute-force
sub-directory names in the root directory and other discovered directories.
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallJavaonWindows);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallOWASPZAPonWindows);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoinstallJavaonLinuxDebianUbuntuKali);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallOWASPZAPonUbuntu);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallOWASPZAPonLinux);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoCreateShortcutforOWASPZAPLinux);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallandConfigureFoxyProxywithFirefox);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoProxyWebTrafficthroughOWASPZAP);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInterceptHTTPRequestswithOWASPZAP);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoSpideraWebSitewithOWASPZAP);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPZAPBreakpointsPart1TrappingHTTPRequests);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPZAPBreakpointsPart2TrappingSpecificHTTPRequests);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoFuzzWebApplicationswithOWASPZAPPart1);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoFuzzWebApplicationswithOWASPZAPPart2);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPZAPWebAppVulnerabilityAssessmentSinglePage);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPZAPAutomatedWebAppVulnerabilityAssessmentEntireSite);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPZAPWebAppVulnerabilityAssessmentPartialSite);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoStartOWASPZAPfromCommandLine);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->ExtendingOWASPZAPwithAddOns);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->UsingOWASPZAPwithBurpSuiteBestofBothWorlds);?>
<br/><br/>