<table class="hint-table">
	<tr class="hint-header" 
		id="idNoHintFoundHintHeader"
		title="Click to open this section"
		onclick="toggleBody(this, window.document.getElementById('idNoHintFoundHintBody'), window.document.getElementById('idNoHintFoundHintHeaderImage'));"
		onmouseover="this.style.backgroundColor='#cccccc';this.style.color='#ffffff';"
		onmouseout="this.style.backgroundColor='#FFFFFF';this.style.color='#000000';"
	>
		<td><img id="idNoHintFoundHintHeaderImage" align="left" style="padding-right: 5px;" alt="Expand No Hints Found" src="./images/down_arrow_16_16.png" />
			No Hints Found
		</td>
	</tr>
	<tr id="idNoHintFoundHintBody" style="display: none;">
		<td class="hint-body">
			<br/>
			<span class="report-header">Sorry. No hints found for this page</span>
			<br/><br/>
		</td>
	</tr>
</table>			