<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
It is possible to use SQL injection on the User Info page to extract user data
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->WhatisSQLInjection);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab8Walkthrough);?>
<br/>