<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Start TCPDump listening on the Mutillidae server. Login to Mutillidae. User TCPDump to intercept credentials
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallWiresharkinWindows10);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->IntroductiontoNetworkPacketAnalysiswithWireshark);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->IntroductiontoPacketAnalysisPart7CapturingNetworkTrafficwithTCPDumpPart1);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->IntroductiontoPacketAnalysisPart8CapturingNetworkTrafficwithTCPDumpPart2);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->IntroductiontoPacketAnalysisPart9PacketAnalysiswithWiresharkPart1);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->IntroductiontoPacketAnalysisPart10PacketAnalysiswithWiresharkPart2);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab2Walkthrough);?>
<br/>
