<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Poison the log file with a PHP command. Load the log file using the insecure direct object reference in the Page parameter.
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->WhatisInsecureDirectObjectReferenceIDOR);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab21Walkthrough);?>
<br/><br/>