<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Examine the input element to understand why the field vanishes
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HTMLControlsarenotSecurityControls);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab5Walkthrough);?>
<br/>