<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Create a web shell on your host. Serve the web shell using a web server. Use the remote file inclusion vulnerability to cause the Mutillidae page to load your PHP file from your host.<span id="videos" class="report-header">Videos</span>
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->WhatisInsecureDirectObjectReferenceIDOR);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab22Walkthrough);?>
<br/><br/>