<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Use the GNU file command to determine the type of content inside
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoIdentifyaFilesType);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab43Walkthrough);?>
<br/>
