			<br/><br/>
			<span class="report-header">Overview</span>
			<br/><br/>
			User Agent Impersonation is altering the configutation of the browser
			in order to change the browsers fingerprint so that the new
			fingerprint matches another browser.
<br/><br/>
<a href="#videos" class="label"><img alt="YouTube" src="/images/youtube-play-icon-40-40.png" style="margin-right: 10px;" />Video Tutorials</a>
			<br/><br/>
			<span class="report-header">Exploitation</span>
			<br/><br/>
			To get started impersonating a user-agent, try a tool
			like User-Agent Switcher; a free
			add-on for Firefox
			<br/><br/>
			Some of the configurations have to be changed by changing
			the browsers configuration. In Firefox, see about:config. Use
			Google to determine how to change the configuration values.
			<br/><br/>
			The validator on this page is itself a JavaScript. The validator
			source code can be read to determine what values are required. Also
			the javascript could be manipulated or even rewritten to beat the
			challenge. There is no security in javascript.
			<br/><br/>
			<span id="videos" class="report-header">Videos</span>
			<br/><br/>
			<br/><br/>