<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Install OWASP Dependency Check if not already installed. Scan the Mutillidae II source code in /var/www/mutillidae with OWASP Dependency Check. Use the information in the report to determine which JavaScript libraries are not patched.
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPDependencyCheckPart1HowtoInstall);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->OWASPDependencyCheckPart2HowtoScanYourProject);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab63Walkthrough);?>
<br/>