<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
First, create an HTTP request that uses the GET method to exploit the cross-site request forgery vulnerability in the Voting page. Change the HTTP GET request to an HTTP POST request and resubmit the request that attempts cross-site request forgery
<span id="videos" class="report-header">Videos</span>
<br/><br/>
No videos for this  hint
<br/>