<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Use Wireshark to observe the browser user-agent string
<br/><br/>
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoInstallJavaonWindows); ?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoinstallJavaonLinuxDebianUbuntuKali); ?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->BurpSuite2HowtoInstallonWindows); ?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->BurpSuite2HowtoInstallonLinux); ?>
<br/>