<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Install the Retire.js plugin into a web browser. Browse to the Mutillidae web site home page. Note the issues found by the Retire.js plugin
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->CheckforVulnerableLibrariesinYourWebApplication);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab62Walkthrough);?>
<br/>