<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Scan the Mutillidae web site with Nikto
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->HowtoScanforWebVulnerabilitieswithNikto);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab51Walkthrough);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab51WalkthroughAlternate);?>
<br/>
