<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
It is possible to use SQL injection on the Login page to bypass authentication
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->WhatisSQLInjection);?>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab7Walkthrough);?>
<br/>