<br/><br/>
<span class="report-header">Lab Hint</span>
<br/><br/>
Cross-site request forgery attacks can be launched from any site against any site. There is no need for the cross-site script exploit that launches the cross-site request forgery attack to be in the same domain as the site vulnerable to cross-site request forgery.
<br/><br/>
<span id="videos" class="report-header">Videos</span>
<br/><br/>
<?php echo $YouTubeVideoHandler->getYouTubeVideo($YouTubeVideoHandler->MutillidaeLab30Walkthrough);?>
<br/><br/>